"use server";

import { prisma } from "@/lib/prisma";
import { PurchaseFilters } from "./types";
import { purchaseSchema, PurchaseFormValues } from "./validations";
import { InventoryService } from "@/features/inventory/inventory.service";
import { PurchaseNumberService } from "./purchaseNumber.service";
import { Prisma, PurchaseStatus, PurchasePaymentStatus } from "@prisma/client";

/**
 * Fetch purchases list with pagination, search, and filters.
 */
export async function getPurchases(filters: PurchaseFilters) {
  try {
    const page = filters.page || 1;
    const limit = filters.limit || 10;
    const skip = (page - 1) * limit;

    const where: Prisma.PurchaseWhereInput = {};

    if (filters.status) {
      where.status = filters.status;
    }

    if (filters.paymentStatus) {
      where.paymentStatus = filters.paymentStatus;
    }

    if (filters.search) {
      where.OR = [
        {
          purchaseNumber: {
            contains: filters.search,
            mode: "insensitive",
          },
        },
        {
          supplierInvoiceNumber: {
            contains: filters.search,
            mode: "insensitive",
          },
        },
        {
          supplier: {
            name: {
              contains: filters.search,
              mode: "insensitive",
            },
          },
        },
      ];
    }

    const [items, total] = await Promise.all([
      prisma.purchase.findMany({
        where,
        include: {
          supplier: {
            select: {
              name: true,
            },
          },
        },
        orderBy: {
          purchaseDate: "desc",
        },
        skip,
        take: limit,
      }),
      prisma.purchase.count({ where }),
    ]);

    const formattedItems = items.map((item: any) => ({
      id: item.id,
      purchaseNumber: item.purchaseNumber,
      supplierInvoiceNumber: item.supplierInvoiceNumber,
      purchaseDate: item.purchaseDate,
      supplierName: item.supplier.name,
      grandTotal: Number(item.grandTotal),
      status: item.status,
      paymentStatus: item.paymentStatus,
      createdAt: item.createdAt,
    }));

    return {
      success: true,
      data: formattedItems,
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  } catch (error: any) {
    console.error("getPurchases error:", error);
    return {
      success: false,
      error: "Failed to fetch purchases.",
    };
  }
}

/**
 * Fetch a single purchase invoice with complete details.
 */
export async function getPurchaseDetails(id: string) {
  try {
    const purchase = await prisma.purchase.findUnique({
      where: { id },
      include: {
        supplier: true,
        items: {
          include: {
            product: {
              include: {
                unit: true,
              },
            },
          },
        },
      },
    });

    if (!purchase) {
      return { success: false, error: "Purchase not found." };
    }

    // Fetch payments associated with this purchase invoice
    const payments = await prisma.payment.findMany({
      where: {
        purchaseId: id,
      },
      orderBy: {
        paymentDate: "desc",
      },
    });

    // Fetch stock movements generated by this purchase invoice
    const stockMovements = await prisma.stockMovement.findMany({
      where: {
        referenceId: id,
      },
      include: {
        product: {
          select: {
            name: true,
            code: true,
          },
        },
      },
      orderBy: {
        createdAt: "desc",
      },
    });

    // Formatting Decimals to JS Numbers
    const formattedItems = purchase.items.map((item: any) => ({
      id: item.id,
      productId: item.productId,
      productName: item.product.name,
      productCode: item.product.code,
      quantity: Number(item.quantity),
      unitName: item.product.unit?.name || "PCS",
      purchaseRate: Number(item.purchaseRate),
      discount: Number(item.discount),
      lineTotal: Number(item.lineTotal),
      remarks: item.remarks,
    }));

    const totalPaid = payments
      .filter((p) => p.status === "COMPLETED")
      .reduce((sum, p) => sum + Number(p.amount), 0);

    const grandTotal = Number(purchase.grandTotal);
    const remainingBalance = Math.max(0, grandTotal - totalPaid);

    const formattedPurchase = {
      id: purchase.id,
      purchaseNumber: purchase.purchaseNumber,
      supplierId: purchase.supplierId,
      supplierName: purchase.supplier.name,
      supplierPhone: purchase.supplier.phone,
      supplierGst: purchase.supplier.gstNumber,
      purchaseDate: purchase.purchaseDate,
      supplierInvoiceNumber: purchase.supplierInvoiceNumber,
      reference: purchase.reference,
      notes: purchase.notes,
      discount: Number(purchase.discount),
      transportCharges: Number(purchase.transportCharges),
      subtotal: Number(purchase.subtotal),
      grandTotal,
      status: purchase.status,
      paymentStatus: purchase.paymentStatus,
      createdAt: purchase.createdAt,
      items: formattedItems,
      totalPaid,
      remainingBalance,
      payments: payments.map((p) => ({
        id: p.id,
        paymentNumber: p.paymentNumber,
        amount: Number(p.amount),
        paymentDate: p.paymentDate,
        paymentMethod: p.paymentMethod,
        referenceNumber: p.referenceNumber,
        notes: p.notes,
        status: p.status,
        cancellationReason: p.cancellationReason,
      })),
      stockMovements: stockMovements.map((sm: any) => ({
        id: sm.id,
        productName: sm.product.name,
        productCode: sm.product.code,
        quantity: Number(sm.quantity),
        type: sm.type,
        createdAt: sm.createdAt,
        notes: sm.notes,
      })),
    };

    return { success: true, data: formattedPurchase };
  } catch (error: any) {
    console.error("getPurchaseDetails error:", error);
    return { success: false, error: "Failed to load purchase details." };
  }
}

/**
 * Create a new purchase invoice.
 */
export async function createPurchase(rawData: any) {
  try {
    // 1. Zod Validation
    const parsed = purchaseSchema.safeParse(rawData);
    if (!parsed.success) {
      const messages = parsed.error.issues.map((i) => i.message).join(", ");
      return { success: false, error: messages };
    }

    const values = parsed.data;

    // 2. Resolve unit IDs and merge duplicate product lines
    const resolvedProductIds = values.items.map((i) => i.productId);
    const dbProducts = await prisma.product.findMany({
      where: { id: { in: resolvedProductIds } },
      select: { id: true, unitId: true },
    });

    const productUnitMap = new Map<string, string>();
    dbProducts.forEach((p: any) => {
      if (p.unitId) {
        productUnitMap.set(p.id, p.unitId);
      }
    });

    const mergedMap = new Map<string, { quantity: number; purchaseRate: number; discount: number; remarks: string }>();

    for (const item of values.items) {
      const existing = mergedMap.get(item.productId);
      const itemRemarks = item.remarks || "";
      if (existing) {
        const nextQty = existing.quantity + item.quantity;
        const totalCostBefore = existing.quantity * existing.purchaseRate;
        const totalCostCurrent = item.quantity * item.purchaseRate;
        const nextRate = nextQty > 0 ? (totalCostBefore + totalCostCurrent) / nextQty : item.purchaseRate;
        const nextDiscount = existing.discount + item.discount;
        const nextRemarks = [existing.remarks, itemRemarks].filter(Boolean).join("; ");

        mergedMap.set(item.productId, {
          quantity: nextQty,
          purchaseRate: nextRate,
          discount: nextDiscount,
          remarks: nextRemarks,
        });
      } else {
        mergedMap.set(item.productId, {
          quantity: item.quantity,
          purchaseRate: item.purchaseRate,
          discount: item.discount,
          remarks: itemRemarks,
        });
      }
    }

    let subtotal = new Prisma.Decimal(0);
    const finalItems = Array.from(mergedMap.entries()).map(([productId, val]) => {
      const qty = new Prisma.Decimal(val.quantity);
      const rate = new Prisma.Decimal(val.purchaseRate);
      const disc = new Prisma.Decimal(val.discount);
      const lineTotal = qty.mul(rate).sub(disc);

      subtotal = subtotal.add(lineTotal);

      const unitId = productUnitMap.get(productId);
      if (!unitId) {
        throw new Error(`Product unit mapping not found for ID: ${productId}`);
      }

      return {
        productId,
        quantity: qty,
        unitId,
        purchaseRate: rate,
        discount: disc,
        lineTotal,
        remarks: val.remarks || null,
      };
    });

    const discHeader = new Prisma.Decimal(values.discount);
    const transport = new Prisma.Decimal(values.transportCharges);
    const grandTotal = subtotal.sub(discHeader).add(transport);

    if (grandTotal.lessThan(0)) {
      return { success: false, error: "Grand total cannot be negative." };
    }

    // 3. Database transaction wrapper
    const result = await prisma.$transaction(async (tx: Prisma.TransactionClient) => {
      // Create sequence number
      const purchaseNumber = await PurchaseNumberService.generateNextPurchaseNumber(tx);

      // Create Purchase Invoice Header
      const purchase = await tx.purchase.create({
        data: {
          purchaseNumber,
          supplierId: values.supplierId,
          purchaseDate: values.purchaseDate,
          supplierInvoiceNumber: values.supplierInvoiceNumber,
          reference: values.reference,
          notes: values.notes,
          discount: discHeader,
          transportCharges: transport,
          subtotal,
          grandTotal,
          status: values.status,
          paymentStatus: "UNPAID",
          items: {
            create: finalItems,
          },
        },
      });

      // If COMPLETED, adjust stock and increase supplier outstanding balance
      if (values.status === "COMPLETED") {
        for (const item of finalItems) {
          await InventoryService.increaseStock(
            tx,
            item.productId,
            item.quantity,
            "PURCHASE",
            purchase.id,
            `Purchase Invoice: ${purchaseNumber}`
          );
        }

        // No outstanding balance update stored on Contact
      }

      return purchase;
    });

    return { success: true, data: { id: result.id, purchaseNumber: result.purchaseNumber } };
  } catch (error: any) {
    console.error("createPurchase action error:", error);
    return {
      success: false,
      error: error.message || "Unique constraint or database server transaction error.",
    };
  }
}

/**
 * Cancel a completed purchase invoice.
 * Reverses stock levels and reduces outstanding balance.
 */
export async function cancelPurchase(id: string) {
  try {
    const purchase = await prisma.purchase.findUnique({
      where: { id },
      include: {
        items: true,
      },
    });

    if (!purchase) {
      return { success: false, error: "Purchase invoice not found." };
    }

    if (purchase.status === "CANCELLED") {
      return { success: false, error: "Purchase is already cancelled." };
    }

    const originalStatus = purchase.status;

    const result = await prisma.$transaction(async (tx: Prisma.TransactionClient) => {
      const updated = await tx.purchase.update({
        where: { id },
        data: {
          status: "CANCELLED",
        },
      });

      // Only reverse inventory and outstanding if it was COMPLETED (drafts haven't changed counts)
      if (originalStatus === "COMPLETED") {
        for (const item of purchase.items) {
          await InventoryService.reverseStock(
            tx,
            item.productId,
            item.quantity,
            "PURCHASE",
            id,
            `Reversal: Cancelled invoice ${purchase.purchaseNumber}`
          );
        }

        // No outstanding balance update stored on Contact
      }

      return updated;
    });

    return { success: true, data: { id: result.id, status: result.status } };
  } catch (error: any) {
    console.error("cancelPurchase action error:", error);
    return { success: false, error: error.message || "Failed to cancel purchase invoice." };
  }
}

/**
 * Fetch list of suppliers for select selectors.
 */
export async function getSuppliersList() {
  try {
    const list = await prisma.contact.findMany({
      where: {
        type: "SUPPLIER",
        isActive: true,
      },
      select: {
        id: true,
        name: true,
      },
      orderBy: {
        name: "asc",
      },
    });
    return { success: true, data: list };
  } catch (error) {
    console.error("getSuppliersList error:", error);
    return { success: false, error: "Failed to load suppliers." };
  }
}

/**
 * Fetch brief metrics for purchase dashboard analytics.
 */
export async function getPurchaseDashboardMetrics() {
  try {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const completedStatus: PurchaseStatus = "COMPLETED";

    const [allCompleted, todayCompleted, pendingPayments] = await Promise.all([
      // 1. Total Purchases
      prisma.purchase.aggregate({
        where: { status: completedStatus },
        _sum: { grandTotal: true },
      }),
      // 2. Today's Purchases
      prisma.purchase.aggregate({
        where: {
          status: completedStatus,
          purchaseDate: {
            gte: today,
          },
        },
        _sum: { grandTotal: true },
      }),
      // 3. Pending Payments
      prisma.purchase.aggregate({
        where: {
          status: completedStatus,
          paymentStatus: {
            in: ["UNPAID", "PARTIALLY_PAID"] as PurchasePaymentStatus[],
          },
        },
        _sum: { grandTotal: true },
      }),
    ]);

    return {
      success: true,
      data: {
        totalPurchases: Number(allCompleted._sum.grandTotal || 0),
        todayPurchases: Number(todayCompleted._sum.grandTotal || 0),
        pendingPayments: Number(pendingPayments._sum.grandTotal || 0),
      },
    };
  } catch (error) {
    console.error("getPurchaseDashboardMetrics error:", error);
    return { success: false, error: "Failed to load dashboard metrics." };
  }
}

/**
 * Fetch list of active products for purchase creation dropdown.
 */
export async function getProductsList() {
  try {
    const list = await prisma.product.findMany({
      where: {
        isActive: true,
      },
      select: {
        id: true,
        code: true,
        name: true,
        type: true,
        volumeMl: true,
        color: true,
        purchasePrice: true,
        unitId: true,
        unit: {
          select: {
            name: true,
          },
        },
      },
      orderBy: {
        name: "asc",
      },
    });
    return {
      success: true,
      data: list.map((p: any) => ({
        id: p.id,
        code: p.code,
        name: p.name,
        type: p.type,
        volumeMl: p.volumeMl,
        color: p.color,
        purchasePrice: p.purchasePrice ? Number(p.purchasePrice) : 0,
        unitId: p.unitId || "",
        unitName: p.unit?.name || "PCS",
      })),
    };
  } catch (error) {
    console.error("getProductsList error:", error);
    return { success: false, error: "Failed to load products." };
  }
}
