import { Prisma, PrismaClient, PurchaseStatus, PurchasePaymentStatus } from "@prisma/client";
import { InventoryService } from "@/features/inventory/inventory.service";
import { NumberGeneratorService } from "@/features/shared/services/numberGenerator.service";
import { PurchaseFilters } from "./types";
import { CreatePurchaseDTO } from "./validations";

export const PurchaseService = {
  /**
   * Calculates totals (subtotal, grandTotal) for purchase lines.
   */
  calculatePurchaseTotals(
    items: { quantity: number; purchaseRate: number; discount: number }[],
    discountHeader: number,
    transportCharges: number
  ) {
    let subtotal = new Prisma.Decimal(0);
    const lineTotals = items.map((item) => {
      const qty = new Prisma.Decimal(item.quantity);
      const rate = new Prisma.Decimal(item.purchaseRate);
      const disc = new Prisma.Decimal(item.discount);
      const lineTotal = qty.mul(rate).sub(disc);
      subtotal = subtotal.add(lineTotal);
      return lineTotal;
    });

    const discHeader = new Prisma.Decimal(discountHeader);
    const transport = new Prisma.Decimal(transportCharges);
    const grandTotal = subtotal.sub(discHeader).add(transport);

    return {
      subtotal,
      grandTotal,
      lineTotals,
    };
  },

  /**
   * Validates supplier profile rules.
   */
  async validatePurchaseSupplier(supplierId: string, tx: Prisma.TransactionClient) {
    const supplier = await tx.contact.findUnique({
      where: { id: supplierId },
      select: { type: true, isActive: true },
    });

    if (!supplier) {
      throw new Error("Supplier profile does not exist.");
    }
    if (supplier.type !== "SUPPLIER") {
      throw new Error("The selected profile is not registered as a supplier.");
    }
    if (!supplier.isActive) {
      throw new Error("Cannot log transactions for an inactive supplier.");
    }
  },

  /**
   * Fetch purchases list.
   */
  async getPurchases(filters: PurchaseFilters, client: PrismaClient | Prisma.TransactionClient) {
    const page = filters.page || 1;
    const limit = filters.limit || 10;
    const skip = (page - 1) * limit;

    const where: Prisma.PurchaseWhereInput = {};

    if (filters.status) {
      where.status = filters.status;
    }

    if (filters.paymentStatus) {
      where.paymentStatus = filters.paymentStatus;
    }

    if (filters.search) {
      where.OR = [
        {
          purchaseNumber: {
            contains: filters.search,
            mode: "insensitive",
          },
        },
        {
          supplierInvoiceNumber: {
            contains: filters.search,
            mode: "insensitive",
          },
        },
        {
          supplier: {
            name: {
              contains: filters.search,
              mode: "insensitive",
            },
          },
        },
      ];
    }

    const [items, total] = await Promise.all([
      client.purchase.findMany({
        where,
        include: {
          supplier: {
            select: {
              name: true,
            },
          },
        },
        orderBy: {
          purchaseDate: "desc",
        },
        skip,
        take: limit,
      }),
      client.purchase.count({ where }),
    ]);

    const formattedItems = items.map((item: any) => ({
      id: item.id,
      purchaseNumber: item.purchaseNumber,
      supplierInvoiceNumber: item.supplierInvoiceNumber,
      purchaseDate: item.purchaseDate,
      supplierName: item.supplier.name,
      grandTotal: Number(item.grandTotal),
      status: item.status,
      paymentStatus: item.paymentStatus,
      createdAt: item.createdAt,
    }));

    return {
      items: formattedItems,
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  },

  /**
   * Fetch a single purchase details.
   */
  async getPurchaseDetails(id: string, client: PrismaClient | Prisma.TransactionClient) {
    const purchase = await client.purchase.findUnique({
      where: { id },
      include: {
        supplier: true,
        items: {
          include: {
            product: {
              include: {
                unit: true,
              },
            },
          },
        },
      },
    });

    if (!purchase) {
      return null;
    }

    // Fetch payments associated with this purchase invoice
    const payments = await client.payment.findMany({
      where: {
        purchaseId: id,
      },
      orderBy: {
        paymentDate: "desc",
      },
    });

    // Fetch stock movements generated by this purchase invoice
    const stockMovements = await client.stockMovement.findMany({
      where: {
        referenceId: id,
      },
      include: {
        product: {
          select: {
            name: true,
            code: true,
          },
        },
      },
      orderBy: {
        createdAt: "desc",
      },
    });

    // Formatting Decimals to JS Numbers
    const formattedItems = purchase.items.map((item: any) => ({
      id: item.id,
      productId: item.productId,
      productName: item.product.name,
      productCode: item.product.code,
      quantity: Number(item.quantity),
      unitName: item.product.unit?.name || "PCS",
      purchaseRate: Number(item.purchaseRate),
      discount: Number(item.discount),
      lineTotal: Number(item.lineTotal),
      remarks: item.remarks,
    }));

    const totalPaid = payments
      .filter((p) => p.status === "COMPLETED")
      .reduce((sum, p) => sum + Number(p.amount), 0);

    const grandTotal = Number(purchase.grandTotal);
    const remainingBalance = Math.max(0, grandTotal - totalPaid);

    return {
      id: purchase.id,
      purchaseNumber: purchase.purchaseNumber,
      supplierId: purchase.supplierId,
      supplierName: purchase.supplier.name,
      supplierPhone: purchase.supplier.phone,
      supplierGst: purchase.supplier.gstNumber,
      purchaseDate: purchase.purchaseDate,
      supplierInvoiceNumber: purchase.supplierInvoiceNumber,
      reference: purchase.reference,
      notes: purchase.notes,
      discount: Number(purchase.discount),
      transportCharges: Number(purchase.transportCharges),
      subtotal: Number(purchase.subtotal),
      grandTotal,
      status: purchase.status,
      paymentStatus: purchase.paymentStatus,
      createdAt: purchase.createdAt,
      items: formattedItems,
      totalPaid,
      remainingBalance,
      payments: payments.map((p) => ({
        id: p.id,
        paymentNumber: p.paymentNumber,
        amount: Number(p.amount),
        paymentDate: p.paymentDate,
        paymentMethod: p.paymentMethod,
        referenceNumber: p.referenceNumber,
        notes: p.notes,
        status: p.status,
        cancellationReason: p.cancellationReason,
      })),
      stockMovements: stockMovements.map((sm: any) => ({
        id: sm.id,
        productName: sm.product.name,
        productCode: sm.product.code,
        quantity: Number(sm.quantity),
        type: sm.type,
        createdAt: sm.createdAt,
        notes: sm.notes,
      })),
    };
  },

  /**
   * Creates a purchase invoice inside a Prisma transaction wrapper.
   */
  async createPurchase(data: CreatePurchaseDTO, tx: Prisma.TransactionClient) {
    // 1. Validate supplier
    await this.validatePurchaseSupplier(data.supplierId, tx);

    // 2. Resolve product unit IDs and merge duplicates
    const productIds = data.items.map((i: any) => i.productId);
    const products = await tx.product.findMany({
      where: { id: { in: productIds } },
      select: { id: true, unitId: true },
    });

    const productUnitMap = new Map<string, string>();
    products.forEach((p: any) => {
      if (p.unitId) {
        productUnitMap.set(p.id, p.unitId);
      }
    });

    const mergedMap = new Map<string, { quantity: number; purchaseRate: number; discount: number; remarks: string }>();

    for (const item of data.items) {
      const existing = mergedMap.get(item.productId);
      const itemRemarks = item.remarks || "";
      if (existing) {
        const nextQty = existing.quantity + item.quantity;
        const totalCostBefore = existing.quantity * existing.purchaseRate;
        const totalCostCurrent = item.quantity * item.purchaseRate;
        const nextRate = nextQty > 0 ? (totalCostBefore + totalCostCurrent) / nextQty : item.purchaseRate;
        const nextDiscount = existing.discount + item.discount;
        const nextRemarks = [existing.remarks, itemRemarks].filter(Boolean).join("; ");

        mergedMap.set(item.productId, {
          quantity: nextQty,
          purchaseRate: nextRate,
          discount: nextDiscount,
          remarks: nextRemarks,
        });
      } else {
        mergedMap.set(item.productId, {
          quantity: item.quantity,
          purchaseRate: item.purchaseRate,
          discount: item.discount,
          remarks: itemRemarks,
        });
      }
    }

    const itemsList = Array.from(mergedMap.entries()).map(([productId, val]) => {
      const unitId = productUnitMap.get(productId);
      if (!unitId) {
        throw new Error(`Product unit mapping not found for ID: ${productId}`);
      }

      return {
        productId,
        quantity: val.quantity,
        unitId,
        purchaseRate: val.purchaseRate,
        discount: val.discount,
        remarks: val.remarks || null,
      };
    });

    // 3. Generate sequential invoice number
    const purchaseNumber = await NumberGeneratorService.generateNumber("PUR", tx);

    // 4. Calculate subtotal & grandTotal
    const { subtotal, grandTotal, lineTotals } = this.calculatePurchaseTotals(
      itemsList,
      data.discount || 0,
      data.transportCharges || 0
    );

    if (grandTotal.lessThan(0)) {
      throw new Error("Grand total cannot be negative.");
    }

    // 5. Create Purchase Invoice Header
    const purchase = await tx.purchase.create({
      data: {
        purchaseNumber,
        supplierId: data.supplierId,
        purchaseDate: data.purchaseDate,
        supplierInvoiceNumber: data.supplierInvoiceNumber || null,
        reference: data.reference || null,
        notes: data.notes || null,
        discount: new Prisma.Decimal(data.discount || 0),
        transportCharges: new Prisma.Decimal(data.transportCharges || 0),
        subtotal,
        grandTotal,
        status: data.status,
        paymentStatus: "UNPAID",
        items: {
          create: itemsList.map((item, idx) => ({
            productId: item.productId,
            quantity: new Prisma.Decimal(item.quantity),
            unitId: item.unitId,
            purchaseRate: new Prisma.Decimal(item.purchaseRate),
            discount: new Prisma.Decimal(item.discount),
            lineTotal: lineTotals[idx],
            remarks: item.remarks,
          })),
        },
      },
      include: {
        items: true,
      },
    });

    // 6. Adjust stock if COMPLETED
    if (data.status === "COMPLETED") {
      for (const item of purchase.items) {
        await InventoryService.increaseStock(
          tx,
          item.productId,
          item.quantity,
          "PURCHASE",
          purchase.id,
          `Purchase Invoice: ${purchaseNumber}`
        );
      }
    }

    return purchase;
  },

  /**
   * Cancels a completed purchase invoice transaction.
   */
  async cancelPurchase(id: string, tx: Prisma.TransactionClient) {
    const purchase = await tx.purchase.findUnique({
      where: { id },
      include: { items: true },
    });

    if (!purchase) {
      throw new Error("Purchase invoice not found.");
    }

    if (purchase.status === "CANCELLED") {
      throw new Error("Purchase is already cancelled.");
    }

    const originalStatus = purchase.status;

    const updated = await tx.purchase.update({
      where: { id },
      data: {
        status: "CANCELLED",
      },
    });

    // Only reverse inventory and outstanding if it was COMPLETED (drafts haven't changed counts)
    if (originalStatus === "COMPLETED") {
      for (const item of purchase.items) {
        await InventoryService.decreaseStock(
          tx,
          item.productId,
          item.quantity,
          "PURCHASE",
          id,
          `Reversal: Cancelled invoice ${purchase.purchaseNumber}`
        );
      }
    }

    return updated;
  },
};
